souffle: souffle::profile::Reader Class Reference
souffle::profile::Reader Class Reference
#include <Reader.h>
Public Member Functions
void addFrequency (std::shared_ptr< Relation > rel, std::vector< std::string > data)
void addIteration (std::shared_ptr< Relation > rel, std::vector< std::string > data)
void addRelation (const DirectoryEntry &relation)
void addRule (std::shared_ptr< Relation > rel, std::vector< std::string > data)
std::string createId ()
bool isLive ()
bool isLoaded ()
void process (const std::vector< std::string > &data)
void processFile ()
Read the contents from file into the class.
Reader (std::string filename, std::shared_ptr< ProgramRun > run)
Reader (std::shared_ptr< ProgramRun > run)
std::string RelationcreateId ()
void save (std::string f_name)
Data Fields
std::shared_ptr< ProgramRun > run
Private Attributes
const ProfileDatabase & db = ProfileEventSingleton::instance().getDB()
std::string file_loc
std::streampos gpos
bool loaded = false
bool online {true}
int rel_id {0}
std::unordered_map
< std::string, std::shared_ptr
< Relation > > relation_map {}
double runtime {0}
Detailed Description
Definition at line 262 of file Reader.h.
Constructor & Destructor Documentation
souffle::profile::Reader::Reader (std::string filename, std::shared_ptr< ProgramRun > run) inline
Definition at line 277 of file Reader.h.
References file_loc, souffle::ProfileEventSingleton::instance(), and souffle::ProfileEventSingleton::setDBFromFile().
                                                               : file_loc(std::move(filename)), run(run) {
         ProfileEventSingleton::instance().setDBFromFile(file_loc);
     }
souffle::profile::Reader::Reader (std::shared_ptr< ProgramRun > run) inline
Definition at line 281 of file Reader.h.
 : run(run) {}
Member Function Documentation
void souffle::profile::Reader::addFrequency (std::shared_ptr< Relation > rel, std::vector< std::string > data) inline
Definition at line 351 of file Reader.h.
Referenced by process().
{
         std::unordered_map<std::string, std::shared_ptr<Rule>>& ruleMap = rel->getRuleMap();
         // If we can't find the rule then it must be an Iteration
         if (ruleMap.find(data[3]) == ruleMap.end()) {
             for (auto& iter : rel->getIterations()) {
                 for (auto& rule : iter->getRul_rec()) {
                     if (rule.second->getVersion() == std::stoi(data[2])) {
                         rule.second->addAtomFrequency(data[4], data[5], std::stoi(data[7]));
                         return;
                     }
                 }
             }
         } else {
             std::shared_ptr<Rule> _rul = ruleMap[data[3]];
             // 0: @frequency-rule;
             // 1: relationName;
             // 2: version;
             // 3: srcloc;
             // 4: stringify(clause);
             // 5: stringify(atom);
             // 6: level;
             // 7: count
             // Generate name from atom + version
             _rul->addAtomFrequency(data[4], data[5], std::stoi(data[7]));
         }
     }
void souffle::profile::Reader::addIteration (std::shared_ptr< Relation > rel, std::vector< std::string > data)
void souffle::profile::Reader::addRelation (const DirectoryEntry & relation) inline
Definition at line 337 of file Reader.h.
References souffle::profile::Entry::accept(), createId(), souffle::profile::Entry::getKey(), souffle::profile::DirectoryEntry::getKeys(), name, souffle::profile::DirectoryEntry::readEntry(), and relation_map.
Referenced by processFile().
{
         const std::string& name = relation.getKey();
         relation_map.emplace(name, std::make_shared<Relation>(name, createId()));
         auto& rel = *relation_map[name];
         RelationVisitor relationVisitor(rel);
         for (const auto& key : relation.getKeys()) {
             relation.readEntry(key)->accept(relationVisitor);
         }
     }
void souffle::profile::Reader::addRule (std::shared_ptr< Relation > rel, std::vector< std::string > data)
std::string souffle::profile::Reader::createId () inline
Definition at line 389 of file Reader.h.
References rel_id.
Referenced by addRelation(), and process().
{
         return "R" + std::to_string(++rel_id);
     }
bool souffle::profile::Reader::isLive () inline
Definition at line 333 of file Reader.h.
References online.
{
         return online;
     }
bool souffle::profile::Reader::isLoaded () inline
Definition at line 381 of file Reader.h.
References loaded.
{
         return loaded;
     }
void souffle::profile::Reader::process (const std::vector< std::string > & data) inline
Definition at line 318 of file Reader.h.
References addFrequency(), createId(), relation_map, run, and runtime.
{
         {
             if (data[0].find("frequency") != std::string::npos) {
                 if (relation_map.find(data[1]) == relation_map.end()) {
                     relation_map.emplace(data[1], std::make_shared<Relation>(Relation(data[1], createId())));
                 }
                 std::shared_ptr<Relation> _rel = relation_map[data[1]];
                 addFrequency(_rel, data);
             }
         }
         run->SetRuntime(this->runtime);
         run->setRelation_map(this->relation_map);
     }
void souffle::profile::Reader::processFile () inline
Read the contents from file into the class.
Definition at line 285 of file Reader.h.
References addRelation(), db, souffle::profile::TimeEntry::getTime(), loaded, souffle::profile::ProfileDatabase::lookupEntry(), souffle::now(), online, rel_id, relation, relation_map, relations, run, and runtime.
{
         rel_id = 0;
         relation_map.clear();
         auto programDuration = dynamic_cast<DurationEntry*>(db.lookupEntry({"program", "runtime"}));
         if (programDuration == nullptr) {
             auto startTimeEntry = dynamic_cast<TimeEntry*>(db.lookupEntry({"program", "starttime"}));
             if (startTimeEntry != nullptr) {
                 auto time = startTimeEntry->getTime();
                 runtime = (now().time_since_epoch().count() - time.count()) / 1000000.0;
             }
         } else {
             runtime = (programDuration->getEnd() - programDuration->getStart()).count() / 1000000.0;
             online = false;
         }
         auto relations = dynamic_cast<DirectoryEntry*>(db.lookupEntry({"program", "relation"}));
         if (relations == nullptr) {
             // Souffle hasn't generated any profiling information yet.
             return;
         }
         for (const auto& cur : relations->getKeys()) {
             auto relation = dynamic_cast<DirectoryEntry*>(db.lookupEntry({"program", "relation", cur}));
             if (relation != nullptr) {
                 addRelation(*relation);
             }
         }
         run->SetRuntime(this->runtime);
         run->setRelation_map(this->relation_map);
         loaded = true;
     }
std::string souffle::profile::Reader::RelationcreateId () inline
Definition at line 385 of file Reader.h.
References rel_id.
{
         return "R" + std::to_string(++rel_id);
     }
void souffle::profile::Reader::save (std::string f_name)
Field Documentation
const ProfileDatabase& souffle::profile::Reader::db = ProfileEventSingleton::instance().getDB() private
Definition at line 266 of file Reader.h.
Referenced by processFile().
std::string souffle::profile::Reader::file_loc private
Definition at line 264 of file Reader.h.
Referenced by Reader().
std::streampos souffle::profile::Reader::gpos private
Definition at line 265 of file Reader.h.
bool souffle::profile::Reader::loaded = false private
Definition at line 267 of file Reader.h.
Referenced by isLoaded(), and processFile().
bool souffle::profile::Reader::online {true} private
Definition at line 268 of file Reader.h.
Referenced by isLive(), and processFile().
int souffle::profile::Reader::rel_id {0} private
Definition at line 272 of file Reader.h.
Referenced by createId(), processFile(), and RelationcreateId().
std::unordered_map<std::string, std::shared_ptr<Relation> > souffle::profile::Reader::relation_map {} private
Definition at line 271 of file Reader.h.
Referenced by addRelation(), process(), and processFile().
std::shared_ptr<ProgramRun> souffle::profile::Reader::run
Definition at line 275 of file Reader.h.
Referenced by process(), and processFile().
double souffle::profile::Reader::runtime {0} private
Definition at line 270 of file Reader.h.
Referenced by process(), and processFile().
The documentation for this class was generated from the following file:
profile/Reader.h