souffle: souffle::profile::TimeEntry Class Reference
souffle::profile::TimeEntry Class Reference
Time Entry.
#include <ProfileDatabase.h>
Public Member Functions
void accept (Visitor &v) override
microseconds getTime () const
void print (std::ostream &os, int tabpos) const override
TimeEntry (const std::string &key, microseconds time)
Public Member Functions inherited from souffle::profile::Entry
Entry (std::string key)
const std::string & getKey () const
virtual ~Entry ()=default
Private Attributes
microseconds time
Detailed Description
Time Entry.
Definition at line 235 of file ProfileDatabase.h.
Constructor & Destructor Documentation
souffle::profile::TimeEntry::TimeEntry (const std::string & key, microseconds time) inline
Definition at line 241 of file ProfileDatabase.h.
 : Entry(key), time(time) {}
Member Function Documentation
void souffle::profile::TimeEntry::accept (Visitor & v) inline override virtual
Implements souffle::profile::Entry.
Definition at line 249 of file ProfileDatabase.h.
References souffle::profile::Visitor::visit().
{
         v.visit(*this);
     }
microseconds souffle::profile::TimeEntry::getTime () const inline
Definition at line 244 of file ProfileDatabase.h.
References time.
Referenced by souffle::profile::Reader::processFile().
{
         return time;
     }
void souffle::profile::TimeEntry::print (std::ostream & os, int tabpos) const inline override virtual
Implements souffle::profile::Entry.
Definition at line 254 of file ProfileDatabase.h.
References souffle::profile::Entry::getKey(), and time.
{
         os << std::string(tabpos, ' ') << '"' << getKey();
         os << "\": { \"time\": ";
         os << time.count();
         os << '}';
     }
Field Documentation
microseconds souffle::profile::TimeEntry::time private
Definition at line 238 of file ProfileDatabase.h.
Referenced by getTime(), and print().
The documentation for this class was generated from the following file:
ProfileDatabase.h