souffle: souffle::profile::SizeEntry Class Reference
souffle::profile::SizeEntry Class Reference
SizeEntry.
#include <ProfileDatabase.h>
Public Member Functions
void accept (Visitor &v) override
size_t getSize () const
void print (std::ostream &os, int tabpos) const override
SizeEntry (const std::string &key, size_t size)
Public Member Functions inherited from souffle::profile::Entry
Entry (std::string key)
const std::string & getKey () const
virtual ~Entry ()=default
Private Attributes
size_t size
Detailed Description
SizeEntry.
Definition at line 142 of file ProfileDatabase.h.
Constructor & Destructor Documentation
souffle::profile::SizeEntry::SizeEntry (const std::string & key, size_t size) inline
Definition at line 146 of file ProfileDatabase.h.
 : Entry(key), size(size) {}
Member Function Documentation
void souffle::profile::SizeEntry::accept (Visitor & v) inline override virtual
Implements souffle::profile::Entry.
Definition at line 154 of file ProfileDatabase.h.
References souffle::profile::Visitor::visit().
{
         v.visit(*this);
     }
size_t souffle::profile::SizeEntry::getSize () const inline
Definition at line 149 of file ProfileDatabase.h.
References size.
Referenced by souffle::profile::Counter::visit().
{
         return size;
     }
void souffle::profile::SizeEntry::print (std::ostream & os, int tabpos) const inline override virtual
Implements souffle::profile::Entry.
Definition at line 159 of file ProfileDatabase.h.
References souffle::profile::Entry::getKey(), and size.
{
         os << std::string(tabpos, ' ') << "\"" << getKey() << "\": " << size;
     }
Field Documentation
size_t souffle::profile::SizeEntry::size private
Definition at line 144 of file ProfileDatabase.h.
Referenced by getSize(), and print().
The documentation for this class was generated from the following file:
ProfileDatabase.h