souffle: souffle::profile::Counter Class Reference
souffle::profile::Counter Class Reference
#include <ProfileDatabase.h>
Public Member Functions
Counter (std::string key)
size_t getCounter () const
void visit (SizeEntry &e) override
Public Member Functions inherited from souffle::profile::Visitor
virtual void visit (DirectoryEntry &e)
virtual void visit (DurationEntry &e)
virtual void visit (TextEntry &e)
virtual void visit (TimeEntry &e)
virtual ~Visitor ()=default
Private Attributes
size_t ctr {0}
std::string key
Detailed Description
Definition at line 270 of file ProfileDatabase.h.
Constructor & Destructor Documentation
souffle::profile::Counter::Counter (std::string key) inline
Definition at line 276 of file ProfileDatabase.h.
 : key(std::move(key)) {}
Member Function Documentation
size_t souffle::profile::Counter::getCounter () const inline
Definition at line 283 of file ProfileDatabase.h.
References ctr.
Referenced by souffle::profile::ProfileDatabase::computeSum().
{
         return ctr;
     }
void souffle::profile::Counter::visit (SizeEntry & e) inline override virtual
Reimplemented from souffle::profile::Visitor.
Definition at line 277 of file ProfileDatabase.h.
References ctr, souffle::profile::Entry::getKey(), souffle::profile::SizeEntry::getSize(), and key.
{
         std::cout << "Size entry : " << e.getKey() << " " << e.getSize() << "\n";
         if (e.getKey() == key) {
             ctr += e.getSize();
         }
     }
Field Documentation
size_t souffle::profile::Counter::ctr {0} private
Definition at line 272 of file ProfileDatabase.h.
Referenced by getCounter(), and visit().
std::string souffle::profile::Counter::key private
Definition at line 273 of file ProfileDatabase.h.
Referenced by visit().
The documentation for this class was generated from the following file:
ProfileDatabase.h