souffle: souffle::profile::Entry Class Reference
souffle::profile::Entry Class Reference abstract
Entry class.
#include <ProfileDatabase.h>
Public Member Functions
virtual void accept (Visitor &v)=0
Entry (std::string key)
const std::string & getKey () const
virtual void print (std::ostream &os, int tabpos) const =0
virtual ~Entry ()=default
Private Attributes
std::string key
Detailed Description
Entry class.
abstract class for a key/value entry in a hierarchical database
Definition at line 48 of file ProfileDatabase.h.
Constructor & Destructor Documentation
souffle::profile::Entry::Entry (std::string key) inline
Definition at line 54 of file ProfileDatabase.h.
 : key(std::move(key)) {}
virtual souffle::profile::Entry::~Entry () virtual default
Member Function Documentation
virtual void souffle::profile::Entry::accept (Visitor & v) pure virtual
Implemented in souffle::profile::TimeEntry, souffle::profile::DurationEntry, souffle::profile::TextEntry, souffle::profile::SizeEntry, and souffle::profile::DirectoryEntry.
Referenced by souffle::profile::Reader::addRelation(), and souffle::profile::Visitor::visit().
const std::string& souffle::profile::Entry::getKey () const inline
Definition at line 58 of file ProfileDatabase.h.
References key.
Referenced by souffle::profile::Reader::addRelation(), souffle::profile::DirectoryEntry::print(), souffle::profile::SizeEntry::print(), souffle::profile::TextEntry::print(), souffle::profile::DurationEntry::print(), souffle::profile::TimeEntry::print(), souffle::profile::Visitor::visit(), and souffle::profile::Counter::visit().
{
         return key;
     };
virtual void souffle::profile::Entry::print (std::ostream & os, int tabpos) const pure virtual
Implemented in souffle::profile::TimeEntry, souffle::profile::DurationEntry, souffle::profile::TextEntry, souffle::profile::SizeEntry, and souffle::profile::DirectoryEntry.
Field Documentation
std::string souffle::profile::Entry::key private
Definition at line 51 of file ProfileDatabase.h.
Referenced by getKey(), and souffle::profile::DirectoryEntry::writeEntry().
The documentation for this class was generated from the following file:
ProfileDatabase.h