souffle: souffle::profile::Cli Class Reference
souffle::profile::Cli Class Reference
#include <Cli.h>
Public Member Functions
Cli (int argc, char *argv[])
void error ()
void parse ()
Data Fields
std::vector< std::string > args
Detailed Description
Definition at line 26 of file Cli.h.
Constructor & Destructor Documentation
souffle::profile::Cli::Cli (int argc, char * argv[]) inline
Definition at line 30 of file Cli.h.
References args, and i.
                                 : args() {
         for (int i = 0; i < argc; i++) {
             args.push_back(std::string(argv[i]));
         }
     }
Member Function Documentation
void souffle::profile::Cli::error () inline
Definition at line 36 of file Cli.h.
                  {
         std::cout << "Unknown error.\nTry souffle-profile -h for help.\n";
         exit(1);
     }
void souffle::profile::Cli::parse () inline
Definition at line 41 of file Cli.h.
References args, souffle::profile::Tui::outputJson(), souffle::profile::Tui::runCommand(), souffle::profile::Tui::runProf(), and souffle::profile::Tools::split().
Referenced by main().
                  {
         if (args.size() == 1) {
             std::cout << "No arguments provided.\nTry souffle-profile -h for help.\n";
             exit(1);
         }
         switch (args.at(1).at(0)) {
             case '-':
                 switch (args.at(1).at(args.at(1).length() - 1)) {
                     case 'h':
                         std::cout << "Souffle Profiler" << std::endl
                                   << "Usage: souffle-profile -v | -h | <log-file> [ -c <command> [options] |"
                                      "-j | -l ]"
                                   << std::endl
                                   << "<log-file>            The log file to profile." << std::endl
                                   << "-c <command>          Run the given command on the log file, try with  "
                                      "'-c help' for a list"
                                   << std::endl
                                   << "                      of commands." << std::endl
                                   << "-j                    Generate a GUI (html/js) version of the profiler."
                                   << std::endl
                                   << "-l                    Run the profiler in live mode." << std::endl
                                   << "                      try with '-o help' for more information."
                                   << std::endl
                                   << "-v                    Print the profiler version." << std::endl
                                   << "-h                    Print this help message." << std::endl;
                         break;
                     case 'v':
                         std::cout << "Souffle Profiler v3.0.1\n";
                         break;
                     default:
                         std::cout << "Unknown option " << args.at(1)
                                   << ".\nTry souffle-profile -h for help.\n";
                         exit(1);
                         break;
                 }
                 break;
             default:
                 std::string filename = args.at(1);
                 if (args.size() == 2) {
                     Tui(filename, false, false).runProf();
                 } else {
                     switch (args.at(2).at(args.at(2).length() - 1)) {
                         case 'c':
                             if (args.size() == 3) {
                                 std::cout << "No arguments provided for option " << args.at(2)
                                           << ".\nTry souffle-profile -h for help.\n";
                                 exit(1);
                             }
                             Tui(filename, false, false).runCommand(Tools::split(args.at(3), " "));
                             break;
                         case 'l':
                             Tui(filename, true, false).runProf();
                             break;
                         case 'j':
                             Tui(filename, false, true).outputJson();
                             break;
                     }
                 }
                 break;
         }
     }
Field Documentation
std::vector<std::string> souffle::profile::Cli::args
Definition at line 28 of file Cli.h.
Referenced by Cli(), and parse().
The documentation for this class was generated from the following file:
profile/Cli.h