souffle: souffle::profile::ProfileDatabase Class Reference
souffle::profile::ProfileDatabase Class Reference
Hierarchical databas.
#include <ProfileDatabase.h>
Public Member Functions
void addDurationEntry (std::vector< std::string > qualifier, microseconds start, microseconds end)
void addSizeEntry (std::vector< std::string > qualifier, size_t size)
void addTextEntry (std::vector< std::string > qualifier, const std::string &text)
void addTimeEntry (std::vector< std::string > qualifier, microseconds time)
size_t computeSum (const std::vector< std::string > &qualifier)
Entry *const lookupEntry (const std::vector< std::string > &path) const
Return the entry at the given path.
void print (std::ostream &os) const
ProfileDatabase ()
ProfileDatabase (const std::string &filename)
Protected Member Functions
DirectoryEntry * lookupPath (std::vector< std::string > path)
Find path: if directories along the path do not exist, create them.
void parseJson (const json11::Json &json, std::unique_ptr< DirectoryEntry > &node)
Private Attributes
std::unique_ptr< DirectoryEntry > root
Detailed Description
Hierarchical databas.
Definition at line 291 of file ProfileDatabase.h.
Constructor & Destructor Documentation
souffle::profile::ProfileDatabase::ProfileDatabase () inline
Definition at line 345 of file ProfileDatabase.h.
 : root(std::unique_ptr<DirectoryEntry>(new DirectoryEntry("root"))) {}
souffle::profile::ProfileDatabase::ProfileDatabase (const std::string & filename) inline
Definition at line 347 of file ProfileDatabase.h.
References json11::Json::parse().
                                                : root(std::make_unique<DirectoryEntry>("root")) {
         std::ifstream file(filename);
         if (!file.is_open()) {
             std::cerr << "Log file could not be opened." << std::endl;
             exit(1);
         }
         std::string jsonString((std::istreambuf_iterator<char>(file)), (std::istreambuf_iterator<char>()));
         std::string error;
         json11::Json json = json11::Json::parse(jsonString, error);
         if (!error.empty()) {
             std::cerr << "Parse error: " << error << std::endl;
         }
         parseJson(json["root"], root);
     }
Member Function Documentation
void souffle::profile::ProfileDatabase::addDurationEntry (std::vector< std::string > qualifier, microseconds start, microseconds end) inline
Definition at line 385 of file ProfileDatabase.h.
Referenced by souffle::profile::NonRecursiveRuleTimingProcessor::process(), souffle::profile::RecursiveRuleTimingProcessor::process(), souffle::profile::NonRecursiveRelationTimingProcessor::process(), souffle::profile::RecursiveRelationTimingProcessor::process(), souffle::profile::RecursiveRelationCopyTimingProcessor::process(), souffle::profile::RelationIOTimingProcessor::process(), and souffle::profile::ProgramRuntimeProcessor::process().
{
         assert(qualifier.size() > 0 && "no qualifier");
         std::vector<std::string> path(qualifier.begin(), qualifier.end() - 1);
         DirectoryEntry* dir = lookupPath(path);
         const std::string& key = qualifier.back();
         std::unique_ptr<DurationEntry> entry = std::make_unique<DurationEntry>(key, start, end);
         dir->writeEntry(std::move(entry));
     }
void souffle::profile::ProfileDatabase::addSizeEntry (std::vector< std::string > qualifier, size_t size) inline
Definition at line 363 of file ProfileDatabase.h.
Referenced by souffle::profile::NonRecursiveRuleTimingProcessor::process(), souffle::profile::NonRecursiveRuleNumberProcessor::process(), souffle::profile::RecursiveRuleTimingProcessor::process(), souffle::profile::RecursiveRuleNumberProcessor::process(), souffle::profile::NonRecursiveRelationTimingProcessor::process(), souffle::profile::NonRecursiveRelationNumberProcessor::process(), souffle::profile::RecursiveRelationTimingProcessor::process(), souffle::profile::RecursiveRelationNumberProcessor::process(), souffle::profile::RecursiveRelationCopyTimingProcessor::process(), souffle::profile::ProgramResourceUtilisationProcessor::process(), and souffle::profile::FrequencyAtomProcessor::process().
{
         assert(qualifier.size() > 0 && "no qualifier");
         std::vector<std::string> path(qualifier.begin(), qualifier.end() - 1);
         DirectoryEntry* dir = lookupPath(path);
         const std::string& key = qualifier.back();
         std::unique_ptr<SizeEntry> entry = std::make_unique<SizeEntry>(key, size);
         dir->writeEntry(std::move(entry));
     }
void souffle::profile::ProfileDatabase::addTextEntry (std::vector< std::string > qualifier, const std::string & text) inline
Definition at line 374 of file ProfileDatabase.h.
Referenced by souffle::profile::NonRecursiveRuleTimingProcessor::process(), souffle::profile::NonRecursiveRuleNumberProcessor::process(), souffle::profile::RecursiveRuleTimingProcessor::process(), souffle::profile::RecursiveRuleNumberProcessor::process(), souffle::profile::NonRecursiveRelationTimingProcessor::process(), souffle::profile::NonRecursiveRelationNumberProcessor::process(), souffle::profile::RecursiveRelationTimingProcessor::process(), souffle::profile::RecursiveRelationNumberProcessor::process(), souffle::profile::RecursiveRelationCopyTimingProcessor::process(), and souffle::profile::RelationIOTimingProcessor::process().
{
         assert(qualifier.size() > 0 && "no qualifier");
         std::vector<std::string> path(qualifier.begin(), qualifier.end() - 1);
         DirectoryEntry* dir = lookupPath(path);
         const std::string& key = qualifier.back();
         std::unique_ptr<TextEntry> entry = std::make_unique<TextEntry>(key, text);
         dir->writeEntry(std::move(entry));
     }
void souffle::profile::ProfileDatabase::addTimeEntry (std::vector< std::string > qualifier, microseconds time) inline
Definition at line 396 of file ProfileDatabase.h.
Referenced by souffle::profile::ProgramTimepointProcessor::process().
{
         assert(qualifier.size() > 0 && "no qualifier");
         std::vector<std::string> path(qualifier.begin(), qualifier.end() - 1);
         DirectoryEntry* dir = lookupPath(path);
         const std::string& key = qualifier.back();
         std::unique_ptr<TimeEntry> entry = std::make_unique<TimeEntry>(key, time);
         dir->writeEntry(std::move(entry));
     }
size_t souffle::profile::ProfileDatabase::computeSum (const std::vector< std::string > & qualifier) inline
Definition at line 407 of file ProfileDatabase.h.
References souffle::profile::Counter::getCounter().
{
         assert(qualifier.size() > 0 && "no qualifier");
         std::vector<std::string> path(qualifier.begin(), qualifier.end() - 1);
         DirectoryEntry* dir = lookupPath(path);
         const std::string& key = qualifier.back();
         std::cout << "Key: " << key << std::endl;
         Counter ctr(key);
         dir->accept(ctr);
         return ctr.getCounter();
     }
Entry* const souffle::profile::ProfileDatabase::lookupEntry (const std::vector< std::string > & path) const inline
Return the entry at the given path.
Definition at line 422 of file ProfileDatabase.h.
References souffle::profile::DirectoryEntry::readDirectoryEntry(), and souffle::profile::DirectoryEntry::readEntry().
Referenced by souffle::profile::Reader::processFile(), and souffle::profile::Tui::usage().
{
         DirectoryEntry* dir = root.get();
         auto last = --path.end();
         for (auto it = path.begin(); it != last; ++it) {
             dir = dir->readDirectoryEntry(*it);
             if (dir == nullptr) {
                 return nullptr;
             }
         }
         return dir->readEntry(*last);
     }
DirectoryEntry* souffle::profile::ProfileDatabase::lookupPath (std::vector< std::string > path) inline protected
Find path: if directories along the path do not exist, create them.
Definition at line 299 of file ProfileDatabase.h.
References souffle::profile::DirectoryEntry::readDirectoryEntry(), root, and souffle::profile::DirectoryEntry::writeEntry().
{
         DirectoryEntry* dir = root.get();
         for (const std::string& key : path) {
             assert(!key.empty() && "Key is empty!");
             DirectoryEntry* newDir = dir->readDirectoryEntry(key);
             if (newDir == nullptr) {
                 newDir =
                         dynamic_cast<DirectoryEntry*>(dir->writeEntry(std::make_unique<DirectoryEntry>(key)));
             }
             assert(newDir != nullptr && "Attempting to overwrite an existing entry");
             dir = newDir;
         }
         return dir;
     }
void souffle::profile::ProfileDatabase::parseJson (const json11::Json & json, std::unique_ptr< DirectoryEntry > & node) inline protected
Definition at line 314 of file ProfileDatabase.h.
References err, json11::Json::NUMBER, and json11::Json::object_items().
{
         for (auto& cur : json.object_items()) {
             if (cur.second.is_object()) {
                 std::string err;
                 // Duration entries are also maps
                 if (cur.second.has_shape(
                             {{"start", json11::Json::NUMBER}, {"end", json11::Json::NUMBER}}, err)) {
                     auto start = std::chrono::microseconds(cur.second["start"].long_value());
                     auto end = std::chrono::microseconds(cur.second["end"].long_value());
                     node->writeEntry(std::make_unique<DurationEntry>(cur.first, start, end));
                 } else if (cur.second.has_shape({{"time", json11::Json::NUMBER}}, err)) {
                     auto time = std::chrono::microseconds(cur.second["time"].long_value());
                     node->writeEntry(std::make_unique<TimeEntry>(cur.first, time));
                 } else {
                     auto dir = std::make_unique<DirectoryEntry>(cur.first);
                     parseJson(cur.second, dir);
                     node->writeEntry(std::move(dir));
                 }
             } else if (cur.second.is_string()) {
                 node->writeEntry(std::make_unique<TextEntry>(cur.first, cur.second.string_value()));
             } else if (cur.second.is_number()) {
                 node->writeEntry(std::make_unique<SizeEntry>(cur.first, cur.second.long_value()));
             } else {
                 std::string err;
                 cur.second.dump(err);
                 std::cerr << "Unknown types in profile log: " << cur.first << ": " << err << std::endl;
             }
         }
     }
void souffle::profile::ProfileDatabase::print (std::ostream & os) const inline
Definition at line 435 of file ProfileDatabase.h.
Referenced by souffle::ProfileEventSingleton::dump().
{
         os << '{' << std::endl;
         root->print(os, 1);
         os << std::endl << '}' << std::endl;
     };
Field Documentation
std::unique_ptr<DirectoryEntry> souffle::profile::ProfileDatabase::root private
Definition at line 293 of file ProfileDatabase.h.
Referenced by lookupPath().
The documentation for this class was generated from the following file:
ProfileDatabase.h