souffle: souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator Class Reference
souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator Class Reference
The iterator type to be utilized for scanning through btree instances.
#include <BTree.h>
Public Member Functions
iterator ()
iterator (node const *cur, field_index_type pos)
iterator (const iterator &other)
bool operator!= (const iterator &other) const
const Key & operator* () const
iterator & operator++ ()
iterator & operator= (const iterator &other)
bool operator== (const iterator &other) const
void print (std::ostream &out=std::cout) const
Private Attributes
node const * cur
field_index_type pos = 0
Detailed Description
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet>
class souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator
The iterator type to be utilized for scanning through btree instances.
Definition at line 1033 of file BTree.h.
Constructor & Destructor Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::iterator () inline
Definition at line 1042 of file BTree.h.
 : cur(nullptr) {}
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::iterator (node const * cur, field_index_type pos) inline
Definition at line 1045 of file BTree.h.
 : cur(cur), pos(pos) {}
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::iterator (const iterator & other) inline
Definition at line 1048 of file BTree.h.
 : cur(other.cur), pos(other.pos) {}
Member Function Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator!= (const iterator & other) const inline
Definition at line 1063 of file BTree.h.
{
             return !(*this == other);
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> const Key& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator* () const inline
Definition at line 1068 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::cur, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::keys, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::pos.
{
             return cur->keys[pos];
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> iterator& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator++ () inline
Definition at line 1073 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::cur, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChildren(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::getNumElements(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::getParent(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::getPositionInParent(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::isEmpty(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::isInner(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::isLeaf(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::pos.
{
             // the quick mode -- if in a leaf and there are elements left
             if (cur->isLeaf() && ++pos < cur->getNumElements()) {
                 return *this;
             }
             // otherwise it is a bit more tricky
             // A) currently in an inner node => go to the left-most child
             if (cur->isInner()) {
                 cur = cur->getChildren()[pos + 1];
                 while (!cur->isLeaf()) {
                     cur = cur->getChildren()[0];
                 }
                 pos = 0;
                 // nodes may be empty due to biased insertion
                 if (!cur->isEmpty()) {
                     return *this;
                 }
             }
             // B) we are at the right-most element of a leaf => go to next inner node
             assert(cur->isLeaf());
             assert(pos == cur->getNumElements());
             while (cur != nullptr && pos == cur->getNumElements()) {
                 pos = cur->getPositionInParent();
                 cur = cur->getParent();
             }
             return *this;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> iterator& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator= (const iterator & other) inline
Definition at line 1051 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::cur, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::pos.
{
             cur = other.cur;
             pos = other.pos;
             return *this;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator== (const iterator & other) const inline
Definition at line 1058 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::cur, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::pos.
{
             return cur == other.cur && pos == other.pos;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::print (std::ostream & out = std::cout) const inline
Definition at line 1107 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::cur, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::pos.
{
             out << cur << "[" << (int)pos << "]";
         }
Field Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> node const* souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::cur private
Definition at line 1035 of file BTree.h.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator*(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator++(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator=(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator==(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::print().
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> field_index_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::pos = 0 private
Definition at line 1038 of file BTree.h.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator*(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator++(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator=(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator==(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::print().
The documentation for this class was generated from the following file:
BTree.h