souffle: souffle::ProfileEventSingleton::ProfileTimer Class Reference
souffle::ProfileEventSingleton::ProfileTimer Class Reference
Profile Timer.
Public Member Functions
ProfileTimer (uint32_t interval=10)
void resetTimerInterval (uint32_t interval=10)
Reset timer interval.
void start ()
start timer on the thread th
void stop ()
stop timer on the thread th
Private Member Functions
uint32_t getInterval ()
void increaseInterval ()
Increase value of time interval by factor of 2.
void run ()
run method for thread th
Private Attributes
uint32_t runCount = 0
number of utilisation events
bool running = false
timer is running
uint32_t t
time interval between per utilisation read
std::thread th
thread timer runs on
Detailed Description
Profile Timer.
Definition at line 127 of file ProfileEvent.h.
Constructor & Destructor Documentation
souffle::ProfileEventSingleton::ProfileTimer::ProfileTimer (uint32_t interval = 10) inline
Definition at line 166 of file ProfileEvent.h.
 : t(interval) {}
Member Function Documentation
uint32_t souffle::ProfileEventSingleton::ProfileTimer::getInterval () inline private
Definition at line 150 of file ProfileEvent.h.
References t.
Referenced by start().
{
             return t;
         }
void souffle::ProfileEventSingleton::ProfileTimer::increaseInterval () inline private
Increase value of time interval by factor of 2.
Definition at line 155 of file ProfileEvent.h.
References t.
Referenced by run().
{
             // Don't increase time interval past 60 seconds
             if (t < 60000) {
                 t = t * 2;
             }
         }
void souffle::ProfileEventSingleton::ProfileTimer::resetTimerInterval (uint32_t interval = 10) inline
Reset timer interval.
The timer interval increases as the program executes. Resetting the interval is useful to ensure that detailed usage information is gathered even in long running programs, if desired.
Parameters
interval the size of the timing interval in milliseconds
Definition at line 195 of file ProfileEvent.h.
References run(), runCount, and t.
Referenced by souffle::ProfileEventSingleton::resetTimerInterval().
{
             t = interval;
             runCount = 0;
             run();
         }
void souffle::ProfileEventSingleton::ProfileTimer::run () inline private
run method for thread th
Definition at line 142 of file ProfileEvent.h.
References increaseInterval(), souffle::ProfileEventSingleton::instance(), souffle::ProfileEventSingleton::makeUtilisationEvent(), and runCount.
Referenced by resetTimerInterval(), and start().
                    {
             ProfileEventSingleton::instance().makeUtilisationEvent("@utilisation");
             ++runCount;
             if (runCount % 128 == 0) {
                 increaseInterval();
             }
         }
void souffle::ProfileEventSingleton::ProfileTimer::start () inline
start timer on the thread th
Definition at line 169 of file ProfileEvent.h.
References getInterval(), run(), running, and th.
Referenced by souffle::ProfileEventSingleton::startTimer().
                      {
             running = true;
             th = std::thread([this]() {
                 while (running) {
                     run();
                     std::this_thread::sleep_for(std::chrono::milliseconds(getInterval()));
                 }
             });
         }
void souffle::ProfileEventSingleton::ProfileTimer::stop () inline
stop timer on the thread th
Definition at line 181 of file ProfileEvent.h.
References running, and th.
Referenced by souffle::ProfileEventSingleton::stopTimer().
                     {
             running = false;
             if (th.joinable()) {
                 th.join();
             }
         }
Field Documentation
uint32_t souffle::ProfileEventSingleton::ProfileTimer::runCount = 0 private
number of utilisation events
Definition at line 139 of file ProfileEvent.h.
Referenced by resetTimerInterval(), and run().
bool souffle::ProfileEventSingleton::ProfileTimer::running = false private
timer is running
Definition at line 133 of file ProfileEvent.h.
Referenced by start(), and stop().
uint32_t souffle::ProfileEventSingleton::ProfileTimer::t private
time interval between per utilisation read
Definition at line 130 of file ProfileEvent.h.
Referenced by getInterval(), increaseInterval(), and resetTimerInterval().
std::thread souffle::ProfileEventSingleton::ProfileTimer::th private
thread timer runs on
Definition at line 136 of file ProfileEvent.h.
Referenced by start(), and stop().
The documentation for this class was generated from the following file:
ProfileEvent.h