souffle: souffle::profile::Visitor Class Reference
souffle::profile::Visitor Class Reference
Visitor Interface.
#include <ProfileDatabase.h>
Public Member Functions
virtual void visit (DirectoryEntry &e)
virtual void visit (DurationEntry &e)
virtual void visit (SizeEntry &e)
virtual void visit (TextEntry &e)
virtual void visit (TimeEntry &e)
virtual ~Visitor ()=default
Detailed Description
Visitor Interface.
Definition at line 29 of file ProfileDatabase.h.
Constructor & Destructor Documentation
virtual souffle::profile::Visitor::~Visitor () virtual default
Member Function Documentation
void souffle::profile::Visitor::visit (DirectoryEntry & e) inline virtual
Definition at line 262 of file ProfileDatabase.h.
References souffle::profile::Entry::accept(), souffle::profile::Entry::getKey(), souffle::profile::DirectoryEntry::getKeys(), and souffle::profile::DirectoryEntry::readEntry().
Referenced by souffle::profile::DirectoryEntry::accept(), souffle::profile::SizeEntry::accept(), souffle::profile::TextEntry::accept(), souffle::profile::DurationEntry::accept(), and souffle::profile::TimeEntry::accept().
{
     std::cout << "Dir " << e.getKey() << "\n";
     for (const auto& cur : e.getKeys()) {
         std::cout << "\t :" << cur << "\n";
         e.readEntry(cur)->accept(*this);
     }
 }
virtual void souffle::profile::Visitor::visit (DurationEntry & e) inline virtual
Definition at line 37 of file ProfileDatabase.h.
 {}
virtual void souffle::profile::Visitor::visit (SizeEntry & e) inline virtual
Reimplemented in souffle::profile::Counter.
Definition at line 38 of file ProfileDatabase.h.
 {}
virtual void souffle::profile::Visitor::visit (TextEntry & e) inline virtual
Definition at line 39 of file ProfileDatabase.h.
 {}
virtual void souffle::profile::Visitor::visit (TimeEntry & e) inline virtual
Definition at line 40 of file ProfileDatabase.h.
 {}
The documentation for this class was generated from the following file:
ProfileDatabase.h