souffle: souffle::profile::DirectoryEntry Class Reference
souffle::profile::DirectoryEntry Class Reference
DirectoryEntry entry.
#include <ProfileDatabase.h>
Public Member Functions
void accept (Visitor &v) override
DirectoryEntry (const std::string &name)
const std::set< std::string > getKeys () const
void print (std::ostream &os, int tabpos) const override
DirectoryEntry * readDirectoryEntry (const std::string &key) const
Entry * readEntry (const std::string &key) const
Entry * writeEntry (std::unique_ptr< Entry > entry)
Public Member Functions inherited from souffle::profile::Entry
Entry (std::string key)
const std::string & getKey () const
virtual ~Entry ()=default
Private Attributes
std::map< std::string,
std::unique_ptr< Entry > > entries
std::mutex lock
Detailed Description
DirectoryEntry entry.
Definition at line 72 of file ProfileDatabase.h.
Constructor & Destructor Documentation
souffle::profile::DirectoryEntry::DirectoryEntry (const std::string & name) inline
Definition at line 78 of file ProfileDatabase.h.
 : Entry(name) {}
Member Function Documentation
void souffle::profile::DirectoryEntry::accept (Visitor & v) inline override virtual
Implements souffle::profile::Entry.
Definition at line 119 of file ProfileDatabase.h.
References souffle::profile::Visitor::visit().
{
         v.visit(*this);
     }
const std::set<std::string> souffle::profile::DirectoryEntry::getKeys () const inline
Definition at line 81 of file ProfileDatabase.h.
References entries, and lock.
Referenced by souffle::profile::Reader::addRelation(), souffle::profile::Tui::usage(), and souffle::profile::Visitor::visit().
{
         std::set<std::string> result;
         std::lock_guard<std::mutex> guard(lock);
         for (auto const& cur : entries) {
             result.insert(cur.first);
         }
         return result;
     }
void souffle::profile::DirectoryEntry::print (std::ostream & os, int tabpos) const inline override virtual
Implements souffle::profile::Entry.
Definition at line 124 of file ProfileDatabase.h.
References entries, and souffle::profile::Entry::getKey().
{
         os << std::string(tabpos, ' ') << '"' << getKey() << "\": {" << std::endl;
         bool first{true};
         for (auto const& cur : entries) {
             if (!first) {
                 os << ',' << std::endl;
             } else {
                 first = false;
             }
             cur.second->print(os, tabpos + 1);
         }
         os << std::endl << std::string(tabpos, ' ') << '}';
     }
DirectoryEntry* souffle::profile::DirectoryEntry::readDirectoryEntry (const std::string & key) const inline
Definition at line 114 of file ProfileDatabase.h.
References readEntry().
Referenced by souffle::profile::ProfileDatabase::lookupEntry(), souffle::profile::ProfileDatabase::lookupPath(), and souffle::profile::Tui::usage().
{
         return dynamic_cast<DirectoryEntry*>(readEntry(key));
     }
Entry* souffle::profile::DirectoryEntry::readEntry (const std::string & key) const inline
Definition at line 103 of file ProfileDatabase.h.
References entries, and lock.
Referenced by souffle::profile::Reader::addRelation(), souffle::profile::ProfileDatabase::lookupEntry(), readDirectoryEntry(), souffle::profile::Tui::usage(), and souffle::profile::Visitor::visit().
{
         std::lock_guard<std::mutex> guard(lock);
         auto it = entries.find(key);
         if (it != entries.end()) {
             return (*it).second.get();
         } else {
             return nullptr;
         }
     }
Entry* souffle::profile::DirectoryEntry::writeEntry (std::unique_ptr< Entry > entry) inline
Definition at line 91 of file ProfileDatabase.h.
References entries, souffle::profile::Entry::key, and lock.
Referenced by souffle::profile::ProfileDatabase::lookupPath().
{
         assert(entry != nullptr && "null entry");
         std::lock_guard<std::mutex> guard(lock);
         const std::string& key = entry->getKey();
         // Don't rewrite an existing entry
         if (entries.count(key) == 0) {
             entries[key] = std::move(entry);
         }
         return entries[key].get();
     }
Field Documentation
std::map<std::string, std::unique_ptr<Entry> > souffle::profile::DirectoryEntry::entries private
Definition at line 74 of file ProfileDatabase.h.
Referenced by getKeys(), print(), readEntry(), and writeEntry().
std::mutex souffle::profile::DirectoryEntry::lock mutable private
Definition at line 75 of file ProfileDatabase.h.
Referenced by getKeys(), readEntry(), and writeEntry().
The documentation for this class was generated from the following file:
ProfileDatabase.h