souffle: souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node Struct Reference
souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node Struct Reference
The actual, generic node implementation covering the operations for both, inner and leaf nodes.
Public Types
enum { desiredNumKeys = ((blockSize > sizeof(base)) ? blockSize - sizeof(base) : 0) / sizeof(Key), maxKeys = (desiredNumKeys > 3) ? desiredNumKeys : 3 }
Public Member Functions
inner_node & asInnerNode ()
A utility function providing a reference to this node as an inner node.
const inner_node & asInnerNode () const
A utility function providing a reference to this node as a const inner node.
template<typename Comp >
bool check (Comp &comp, const node *root) const
A function to verify the consistency of this node.
node * clone () const
A deep-copy operation creating a clone of this node.
std::vector< chunk > & collectChunks (std::vector< chunk > &res, size_type num, const iterator &begin, const iterator &end) const
A function decomposing the sub-tree rooted by this node into approximately equally sized chunks.
size_type countEntries () const
Counts the number of entries contained in the sub-tree rooted by this node.
size_type countNodes () const
Counts the number of nodes contained in the sub-tree rooted by this node.
node * getChild (size_type s) const
Obtains a reference to the child of the given index.
node ** getChildren ()
Obtains a pointer to the array of child-pointers of this node – if it is an inner node.
node *const * getChildren () const
Obtains a pointer to the array of const child-pointers of this node – if it is an inner node.
size_type getDepth () const
Computes the number of nested levels of the tree rooted by this node.
size_type getMemoryUsage () const
Determines the amount of memory used by the sub-tree rooted by this node.
int getSplitPoint (int)
Obtains the point at which full nodes should be split.
bool isEmpty () const
Checks whether this node is empty – can happen due to biased insertion.
bool isFull () const
Checks whether this node is full.
node (bool inner)
void printTree (std::ostream &out, const std::string &prefix) const
Prints a textual representation of this tree to the given output stream.
int rebalance_or_split (node **root, lock_type &root_lock, int idx)
Moves keys from this node to one of its siblings or splits this node to make some space for the insertion of an element at position idx.
void split (node **root, lock_type &root_lock, int idx)
Splits this node.
~node ()
Public Member Functions inherited from souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base
base (bool inner)
A simple constructor for nodes.
size_type getNumElements () const
node * getParent () const
field_index_type getPositionInParent () const
bool isInner () const
bool isLeaf () const
Data Fields
Key keys [maxKeys]
Data Fields inherited from souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base
const bool inner
size_type numElements
node * parent
field_index_type position
Private Member Functions
void grow_parent (node **root, lock_type &root_lock, node *sibling)
Inserts a new sibling into the parent of this node utilizing the last key of this node as a separation key.
void insert_inner (node **root, lock_type &root_lock, unsigned pos, node *predecessor, const Key &key, node *newNode)
Inserts a new element into an inner node (for internal use only).
Detailed Description
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet>
struct souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node
The actual, generic node implementation covering the operations for both, inner and leaf nodes.
Definition at line 335 of file BTree.h.
Member Enumeration Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> anonymous enum
Enumerator
desiredNumKeys
The number of keys/node desired by the user.
maxKeys
The actual number of keys/node corrected by functional requirements.
Definition at line 336 of file BTree.h.
              {
             /**
              * The number of keys/node desired by the user.
              */
             desiredNumKeys = ((blockSize > sizeof(base)) ? blockSize - sizeof(base) : 0) / sizeof(Key),
             /**
              * The actual number of keys/node corrected by functional requirements.
              */
             maxKeys = (desiredNumKeys > 3) ? desiredNumKeys : 3
         };
Constructor & Destructor Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::node (bool inner) inline
Definition at line 353 of file BTree.h.
 : base(inner) {}
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::~node () inline
Definition at line 356 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::asInnerNode(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::inner_node::cleanup(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::inner.
                 {
             if (this->inner) {
                 asInnerNode().cleanup();
             }
         }
Member Function Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> inner_node& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::asInnerNode () inline
A utility function providing a reference to this node as an inner node.
Definition at line 398 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::inner.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChild(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChildren(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::~node().
{
             assert(this->inner && "Invalid cast!");
             return *static_cast<inner_node*>(this);
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> const inner_node& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::asInnerNode () const inline
A utility function providing a reference to this node as a const inner node.
Definition at line 407 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::inner.
{
             assert(this->inner && "Invalid cast!");
             return *static_cast<const inner_node*>(this);
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> template<typename Comp > bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::check (Comp & comp, const node * root) const inline
A function to verify the consistency of this node.
Parameters
root ... a reference to the root of the enclosing tree.
Returns
true if valid, false otherwise
Definition at line 919 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::check(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::comp, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChildren(), i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::inner, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::keys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::maxKeys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::parent, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::position.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::check(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::check().
{
             bool valid = true;
             // check fill-state
             if (this->numElements > maxKeys) {
                 std::cout << "Node with " << this->numElements << "/" << maxKeys << " encountered!\n";
                 valid = false;
             }
             // check root state
             if (root == this) {
                 if (this->parent != nullptr) {
                     std::cout << "Root not properly linked!\n";
                     valid = false;
                 }
             } else {
                 // check parent relation
                 if (!this->parent) {
                     std::cout << "Invalid null-parent!\n";
                     valid = false;
                 } else {
                     if (this->parent->getChildren()[this->position] != this) {
                         std::cout << "Parent reference invalid!\n";
                         std::cout << "   Node:     " << this << "\n";
                         std::cout << "   Parent:   " << this->parent << "\n";
                         std::cout << "   Position: " << ((int)this->position) << "\n";
                         valid = false;
                     }
                     // check parent key
                     if (valid && this->position != 0 &&
                             !(comp(this->parent->keys[this->position - 1], keys[0]) < ((isSet) ? 0 : 1))) {
                         std::cout << "Left parent key not lower bound!\n";
                         std::cout << "   Node:     " << this << "\n";
                         std::cout << "   Parent:   " << this->parent << "\n";
                         std::cout << "   Position: " << ((int)this->position) << "\n";
                         std::cout << "   Key:   " << (this->parent->keys[this->position]) << "\n";
                         std::cout << "   Lower: " << (keys[0]) << "\n";
                         valid = false;
                     }
                     // check parent key
                     if (valid && this->position != this->parent->numElements &&
                             !(comp(keys[this->numElements - 1], this->parent->keys[this->position]) <
                                     ((isSet) ? 0 : 1))) {
                         std::cout << "Right parent key not lower bound!\n";
                         std::cout << "   Node:     " << this << "\n";
                         std::cout << "   Parent:   " << this->parent << "\n";
                         std::cout << "   Position: " << ((int)this->position) << "\n";
                         std::cout << "   Key:   " << (this->parent->keys[this->position]) << "\n";
                         std::cout << "   Upper: " << (keys[0]) << "\n";
                         valid = false;
                     }
                 }
             }
             // check element order
             if (this->numElements > 0) {
                 for (unsigned i = 0; i < this->numElements - 1; i++) {
                     if (valid && !(comp(keys[i], keys[i + 1]) < ((isSet) ? 0 : 1))) {
                         std::cout << "Element order invalid!\n";
                         std::cout << " @" << this << " key " << i << " is " << keys[i] << " vs "
                                   << keys[i + 1] << "\n";
                         valid = false;
                     }
                 }
             }
             // check state of sub-nodes
             if (this->inner) {
                 for (unsigned i = 0; i <= this->numElements; i++) {
                     valid &= getChildren()[i]->check(comp, root);
                 }
             }
             return valid;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> node* souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::clone () const inline
A deep-copy operation creating a clone of this node.
Definition at line 365 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::clone(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChild(), i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::isInner(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::isLeaf(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::keys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::parent, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::position.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::clone(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::operator=().
{
             // create a clone of this node
             node* res = (this->isInner()) ? static_cast<node*>(new inner_node())
                                           : static_cast<node*>(new leaf_node());
             // copy basic fields
             res->position = this->position;
             res->numElements = this->numElements;
             for (size_type i = 0; i < this->numElements; ++i) {
                 res->keys[i] = this->keys[i];
             }
             // if this is a leaf we are done
             if (this->isLeaf()) {
                 return res;
             }
             // copy child nodes recursively
             auto* ires = (inner_node*)res;
             for (size_type i = 0; i <= this->numElements; ++i) {
                 ires->children[i] = this->getChild(i)->clone();
                 ires->children[i]->parent = res;
             }
             // that's it
             return res;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> std::vector<chunk>& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::collectChunks (std::vector< chunk > & res, size_type num, const iterator & begin, const iterator & end) const inline
A function decomposing the sub-tree rooted by this node into approximately equally sized chunks.
To minimize computational overhead, no strict load balance nor limit on the number of actual chunks is given.
See Also
btree::getChunks()
Parameters
res .. the list of chunks to be extended
num .. the number of chunks to be produced
begin .. the iterator to start the first chunk with
end .. the iterator to end the last chunk with
Returns
the handed in list of chunks extended by generated chunks
Definition at line 854 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::collectChunks(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChild(), i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::isEmpty(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::isLeaf(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::collectChunks(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::getChunks().
{
             assert(num > 0);
             // special case: this node is empty
             if (isEmpty()) {
                 if (begin != end) {
                     res.push_back(chunk(begin, end));
                 }
                 return res;
             }
             // special case: a single chunk is requested
             if (num == 1) {
                 res.push_back(chunk(begin, end));
                 return res;
             }
             // cut-off
             if (this->isLeaf() || num < (this->numElements + 1)) {
                 auto step = this->numElements / num;
                 if (step == 0) {
                     step = 1;
                 }
                 size_type i = 0;
                 // the first chunk starts at the begin
                 res.push_back(chunk(begin, iterator(this, step - 1)));
                 // split up the main part
                 for (i = step - 1; i < this->numElements - step; i += step) {
                     res.push_back(chunk(iterator(this, i), iterator(this, i + step)));
                 }
                 // the last chunk runs to the end
                 res.push_back(chunk(iterator(this, i), end));
                 // done
                 return res;
             }
             // else: collect chunks of sub-set elements
             auto part = num / (this->numElements + 1);
             assert(part > 0);
             getChild(0)->collectChunks(res, part, begin, iterator(this, 0));
             for (size_type i = 1; i < this->numElements; i++) {
                 getChild(i)->collectChunks(res, part, iterator(this, i - 1), iterator(this, i));
             }
             getChild(this->numElements)
                     ->collectChunks(res, num - (part * this->numElements),
                             iterator(this, this->numElements - 1), end);
             // done
             return res;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> size_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::countEntries () const inline
Counts the number of entries contained in the sub-tree rooted by this node.
Definition at line 442 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::countEntries(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChild(), i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::isLeaf(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::countEntries(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::size().
{
             if (this->isLeaf()) {
                 return this->numElements;
             }
             size_type sum = this->numElements;
             for (unsigned i = 0; i <= this->numElements; ++i) {
                 sum += getChild(i)->countEntries();
             }
             return sum;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> size_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::countNodes () const inline
Counts the number of nodes contained in the sub-tree rooted by this node.
Definition at line 427 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::countNodes(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChild(), i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::isLeaf(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::countNodes(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::getNumNodes().
{
             if (this->isLeaf()) {
                 return 1;
             }
             size_type sum = 1;
             for (unsigned i = 0; i <= this->numElements; ++i) {
                 sum += getChild(i)->countNodes();
             }
             return sum;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> node* souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChild (size_type s) const inline
Obtains a reference to the child of the given index.
Definition at line 487 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::asInnerNode(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::inner_node::children.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::clone(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::collectChunks(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::countEntries(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::countNodes(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getDepth(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getMemoryUsage(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::insert_inner(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::load(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::operator=(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::rebalance_or_split().
{
             return asInnerNode().children[s];
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> node** souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChildren () inline
Obtains a pointer to the array of child-pointers of this node – if it is an inner node.
Definition at line 472 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::asInnerNode(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::inner_node::children.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::check(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::insert_inner(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator++(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::printTree(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::split().
{
             return asInnerNode().children;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> node* const* souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChildren () const inline
Obtains a pointer to the array of const child-pointers of this node – if it is an inner node.
Definition at line 480 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::asInnerNode(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::inner_node::children.
{
             return asInnerNode().children;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> size_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getDepth () const inline
Computes the number of nested levels of the tree rooted by this node.
Definition at line 416 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChild(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getDepth(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::isLeaf().
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getDepth(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::getDepth(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::printStats().
{
             if (this->isLeaf()) {
                 return 1;
             }
             return getChild(0)->getDepth() + 1;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> size_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getMemoryUsage () const inline
Determines the amount of memory used by the sub-tree rooted by this node.
Definition at line 457 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChild(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getMemoryUsage(), i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::isLeaf(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getMemoryUsage(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::getMemoryUsage().
{
             if (this->isLeaf()) {
                 return sizeof(leaf_node);
             }
             size_type res = sizeof(inner_node);
             for (unsigned i = 0; i <= this->numElements; ++i) {
                 res += getChild(i)->getMemoryUsage();
             }
             return res;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> int souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getSplitPoint (int) inline
Obtains the point at which full nodes should be split.
Conventional b-trees always split in half. However, in cases where in-order insertions are frequent, a split assigning larger portions to the right fragment provide higher performance and a better node-filling rate.
Definition at line 512 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::maxKeys.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::split().
{
             return std::min(3 * maxKeys / 4, maxKeys - 2);
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::grow_parent (node ** root, lock_type & root_lock, node * sibling) inline private
Inserts a new sibling into the parent of this node utilizing the last key of this node as a separation key.
(for internal use only)
Parameters
root .. a pointer to the root-pointer of the containing tree
sibling .. the new right-sibling to be add to the parent node
Definition at line 689 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::insert_inner(), souffle::OptimisticReadWriteLock::is_write_locked(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::keys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::parent, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::position.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::split().
{
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
             assert(this->lock.is_write_locked());
             assert(!this->parent || this->parent->lock.is_write_locked());
             assert((this->parent != nullptr) || root_lock.is_write_locked());
 #endif
             if (this->parent == nullptr) {
                 assert(*root == this);
                 // create a new root node
                 auto* new_root = new inner_node();
                 new_root->numElements = 1;
                 new_root->keys[0] = keys[this->numElements];
                 new_root->children[0] = this;
                 new_root->children[1] = sibling;
                 // link this and the sibling node to new root
                 this->parent = new_root;
                 sibling->parent = new_root;
                 sibling->position = 1;
                 // switch root node
                 *root = new_root;
             } else {
                 // insert new element in parent element
                 auto parent = this->parent;
                 auto pos = this->position;
                 parent->insert_inner(root, root_lock, pos, this, keys[this->numElements], sibling);
             }
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::insert_inner (node ** root, lock_type & root_lock, unsigned pos, node * predecessor, const Key & key, node * newNode) inline private
Inserts a new element into an inner node (for internal use only).
Parameters
root .. a pointer to the root-pointer of the containing tree
pos .. the position to insert the new key
key .. the key to insert
newNode .. the new right-child of the inserted key
Definition at line 732 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChild(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChildren(), i, souffle::OptimisticReadWriteLock::is_write_locked(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::keys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::maxKeys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::parent, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::position, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::rebalance_or_split().
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::grow_parent().
{
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
             assert(this->lock.is_write_locked());
 #endif
             // check capacity
             if (this->numElements >= maxKeys) {
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
                 assert(!this->parent || this->parent->lock.is_write_locked());
                 assert((this->parent) || root_lock.is_write_locked());
 #endif
                 // split this node
                 pos -= rebalance_or_split(root, root_lock, pos);
                 // complete insertion within new sibling if necessary
                 if (pos > this->numElements) {
                     // correct position
                     pos = pos - this->numElements - 1;
                     // get new sibling
                     auto other = this->parent->getChild(this->position + 1);
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
                     // lock other side
                     other->lock.start_write();
                     // search for new position (since other may have been altered in the meanwhile)
                     size_type i = 0;
                     for (; i <= other->numElements; ++i)
                         if (other->getChild(i) == predecessor) break;
                     pos = (i > other->numElements) ? 0 : i;
 #endif
                     other->insert_inner(root, root_lock, pos, predecessor, key, newNode);
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
                     other->lock.end_write();
 #endif
                     return;
                 }
             }
             // move bigger keys one forward
             for (int i = this->numElements - 1; i >= (int)pos; --i) {
                 keys[i + 1] = keys[i];
                 getChildren()[i + 2] = getChildren()[i + 1];
                 ++getChildren()[i + 2]->position;
             }
             // ensure proper position
             assert(getChild(pos) == predecessor);
             // insert new element
             keys[pos] = key;
             getChildren()[pos + 1] = newNode;
             newNode->parent = this;
             newNode->position = pos + 1;
             ++this->numElements;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::isEmpty () const inline
Checks whether this node is empty – can happen due to biased insertion.
Definition at line 494 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::collectChunks(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator++().
{
             return this->numElements == 0;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::isFull () const inline
Checks whether this node is full.
Definition at line 501 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::maxKeys, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements.
{
             return this->numElements == maxKeys;
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::printTree (std::ostream & out, const std::string & prefix) const inline
Prints a textual representation of this tree to the given output stream.
This feature is mainly intended for debugging and tuning purposes.
See Also
btree::printTree
Definition at line 800 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChildren(), i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::inner, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::keys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::maxKeys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::position.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::printTree().
{
             // print the header
             out << prefix << "@" << this << "[" << ((int)(this->position)) << "] - "
                 << (this->inner ? "i" : "") << "node : " << this->numElements << "/" << maxKeys << " [";
             // print the keys
             for (unsigned i = 0; i < this->numElements; i++) {
                 out << keys[i];
                 if (i != this->numElements - 1) {
                     out << ",";
                 }
             }
             out << "]";
             // print references to children
             if (this->inner) {
                 out << " - [";
                 for (unsigned i = 0; i <= this->numElements; i++) {
                     out << getChildren()[i];
                     if (i != this->numElements) {
                         out << ",";
                     }
                 }
                 out << "]";
             }
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
             // print the lock state
             if (this->lock.is_write_locked()) std::cout << " locked";
 #endif
             out << "\n";
             // print the children recursively
             if (this->inner) {
                 for (unsigned i = 0; i < this->numElements + 1; ++i) {
                     static_cast<const inner_node*>(this)->children[i]->printTree(out, prefix + "    ");
                 }
             }
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> int souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::rebalance_or_split (node ** root, lock_type & root_lock, int idx) inline
Moves keys from this node to one of its siblings or splits this node to make some space for the insertion of an element at position idx.
Returns the number of elements moved to the left side, 0 in case of a split. The number of moved elements will be <= the given idx.
Parameters
root .. the root node of the b-tree being part of
idx .. the position of the insert triggering this operation
Definition at line 584 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::inner_node::children, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChild(), i, souffle::OptimisticReadWriteLock::is_write_locked(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::isInner(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::keys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::maxKeys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::parent, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::position, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::split().
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::insert(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::insert_inner().
{
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
             assert(this->lock.is_write_locked());
             assert(!this->parent || this->parent->lock.is_write_locked());
             assert((this->parent != nullptr) || root_lock.is_write_locked());
 #endif
             // this node is full ... and needs some space
             assert(this->numElements == maxKeys);
             // get snap-shot of parent
             auto parent = this->parent;
             auto pos = this->position;
             // Option A) re-balance data
             if (parent && pos > 0) {
                 node* left = parent->getChild(pos - 1);
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
                 // lock access to left sibling
                 if (!left->lock.try_start_write()) {
                     // left node is currently updated => skip balancing and split
                     split(root, root_lock, idx);
                     return 0;
                 }
 #endif
                 // compute number of elements to be movable to left
                 //    space available in left vs. insertion index
                 size_type num = std::min<int>(maxKeys - left->numElements, idx);
                 // if there are elements to move ..
                 if (num > 0) {
                     Key* splitter = &(parent->keys[this->position - 1]);
                     // .. move keys to left node
                     left->keys[left->numElements] = *splitter;
                     for (size_type i = 0; i < num - 1; ++i) {
                         left->keys[left->numElements + 1 + i] = keys[i];
                     }
                     *splitter = keys[num - 1];
                     // shift keys in this node to the left
                     for (size_type i = 0; i < this->numElements - num; ++i) {
                         keys[i] = keys[i + num];
                     }
                     // .. and children if necessary
                     if (this->isInner()) {
                         auto* ileft = static_cast<inner_node*>(left);
                         auto* iright = static_cast<inner_node*>(this);
                         // move children
                         for (size_type i = 0; i < num; ++i) {
                             ileft->children[left->numElements + i + 1] = iright->children[i];
                         }
                         // update moved children
                         for (size_type i = 0; i < num; ++i) {
                             iright->children[i]->parent = ileft;
                             iright->children[i]->position = left->numElements + i + 1;
                         }
                         // shift child-pointer to the left
                         for (size_type i = 0; i < this->numElements - num + 1; ++i) {
                             iright->children[i] = iright->children[i + num];
                         }
                         // update position of children
                         for (size_type i = 0; i < this->numElements - num + 1; ++i) {
                             iright->children[i]->position = i;
                         }
                     }
                     // update node sizes
                     left->numElements += num;
                     this->numElements -= num;
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
                     left->lock.end_write();
 #endif
                     // done
                     return num;
                 }
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
                 left->lock.abort_write();
 #endif
             }
             // Option B) split node
             split(root, root_lock, idx);
             return 0;  // = no re-balancing
         }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::split (node ** root, lock_type & root_lock, int idx) inline
Splits this node.
Parameters
root .. a pointer to the root-pointer of the enclosing b-tree (might have to be updated if the root-node needs to be split)
idx .. the position of the insert causing the split
Definition at line 523 of file BTree.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::inner_node::children, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getChildren(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::getSplitPoint(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::grow_parent(), i, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::inner, souffle::OptimisticReadWriteLock::is_write_locked(), j, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::keys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::maxKeys, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::numElements, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::parent, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::base::position.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::rebalance_or_split().
{
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
             assert(this->lock.is_write_locked());
             assert(!this->parent || this->parent->lock.is_write_locked());
             assert((this->parent != nullptr) || root_lock.is_write_locked());
 #endif
             assert(this->numElements == maxKeys);
             // get middle element
             int split_point = getSplitPoint(idx);
             // create a new sibling node
             node* sibling = (this->inner) ? static_cast<node*>(new inner_node())
                                           : static_cast<node*>(new leaf_node());
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
             // lock sibling
             sibling->lock.start_write();
 #endif
             // move data over to the new node
             for (unsigned i = split_point + 1, j = 0; i < maxKeys; ++i, ++j) {
                 sibling->keys[j] = keys[i];
             }
             // move child pointers
             if (this->inner) {
                 // move pointers to sibling
                 auto* other = static_cast<inner_node*>(sibling);
                 for (unsigned i = split_point + 1, j = 0; i <= maxKeys; ++i, ++j) {
                     other->children[j] = getChildren()[i];
                     other->children[j]->parent = other;
                     other->children[j]->position = j;
                 }
             }
             // update number of elements
             this->numElements = split_point;
             sibling->numElements = maxKeys - split_point - 1;
             // update parent
             grow_parent(root, root_lock, sibling);
 #if defined(IS_PARALLEL) && !defined(HAS_TSX)
             // unlock sibling
             sibling->lock.end_write();
 #endif
         }
Field Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet> Key souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::keys[maxKeys]
Definition at line 350 of file BTree.h.
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::check(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::clone(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::grow_parent(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true >::insert(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::insert_inner(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::iterator::operator*(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::printTree(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::rebalance_or_split(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet >::node::split().
The documentation for this struct was generated from the following file:
BTree.h